language: python
python:
  - "2.7"
install:
  - "pip install awscli"
sudo: false
cache:
  directories:
    - node_modules
script:
  - "nvm install 0.12"
  - "npm install"
  - "webpack -p --config webpack-prod.config.js"
deploy:
  provider: s3
  access_key_id: AKIAI3ABDFPSOQSGZP3A
  secret_access_key:
    secure: utGsyaThRqoo8a1e1F52xa8bgQrrBUR6/mkSFfYpozZInzDMiQ6di/a2JVbnmmivHNb0jKcnAaY/clDEUq6SqvSSSMgcPKq1dKdCVfEqou4V9NBThBGNJqjaZmLkuhRqcAa79zdHo49hYWpI99hVqEDmYmsqaKBZB90SXuGK+is=
  bucket: stand-by
  skip_cleanup: true
  local-dir: static/build/
  acl: public_read
  on:
    repo: yefim/standby
    branch: master
after_deploy:
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id E22NPM2CZKUNGS --paths "/index.html"
