language: python
python:
- '2.7'
install:
- pip install awscli
sudo: false
cache:
  directories:
  - node_modules
script:
- nvm install stable
- npm install
- webpack -p --config webpack-prod.config.js
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: stand-by
  skip_cleanup: true
  local-dir: static/build/
  acl: public_read
  on:
    repo: yefim/standby
    branch: master
after_deploy:
- aws configure set preview.cloudfront true
- aws cloudfront create-invalidation --distribution-id E22NPM2CZKUNGS --paths "/index.html"
